[package]
name = "nauc"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
indoc = "2.0.5"
itertools = "0.13.0"
rstest = "0.18.2"
thiserror = "1.0.58"
